ls:
  packages/*:
    .ts: camelCase
    .tsx: PascalCase
    .spec.ts: camelCase
    .config.ts: camelCase
    .less: camelCase
    .vue: PascalCase
    .md: PascalCase

  scripts:
    .ts: camelCase
    .config.ts: camelCase
    .svg: kebab-case
